Follow new guidelines for 3rd party repositories on Ubuntu/Debian
qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one pull request #1021
Opened 2022-08-09 07:03 UTC by nicogodet

Here is proposed changes to follow guidelines for third party repositories on Ubuntu and Debian according to https://wiki.debian.org/DebianRepository/UseThirdParty.

2022-08-09 09:22 UTC, eshattow reviewed
sources.list(5) says /usr/share/keyrings for keyrings managed by packages and /etc/apt/keyrings for keyrings managed by the system operator. This was added 2022-05-23 to the https://wiki.debian.org/DebianRepository/UseThirdParty guide "Recommend /etc/apt/keyrings for locally-managed keys, as per apt 2.4.0 changelog".

Also from sources.list(5) says of the Deb822 ".sources" format "It is intended to make this format gradually the default format, deprecating the previously described one-line-style format, as it is easier to create, extend and modify for humans and machines alike..." so would recommend that over continuing with ".list" format

2022-08-09 17:31 UTC, nicogodet commented
@jef-n Key does not need to be dearmored anymore ?

2022-08-09 20:40 UTC, jef-n commented
> @jef-n Key does not need to be dearmored anymore ?

Not the keyring.

```
$ file qgis-2022.gpg.key qgis-archive-keyring.gpg
qgis-2022.gpg.key:        PGP public key block Public-Key (old)
qgis-archive-keyring.gpg: GPG keybox database version 1, created-at Tue Aug  9 16:14:40 2022, last-maintained Tue Aug  9 16:14:40 2022
```

2022-08-10 06:50 UTC, nicogodet commented
I'm very busy right now but I plan to finish this by the end of the week.

2022-08-11 11:29 UTC, agiudiceandrea commented
Please see also https://github.com/qgis/QGIS-Website/issues/947#issuecomment-968061113

2022-08-11 11:33 UTC, nicogodet commented
@agiudiceandrea I planed to fix this too 😉

2022-08-13 06:56 UTC, agiudiceandrea commented on source/site/forusers/alldownloads.rst
> + sudo wget -O/etc/apt/keyrings/qgis-archive-keyring.gpg https://download.qgis.org/downloads/qgis-archive-keyring.gpg
```suggestion
 sudo wget -O /etc/apt/keyrings/qgis-archive-keyring.gpg https://download.qgis.org/downloads/qgis-archive-keyring.gpg
```

2022-08-13 06:57 UTC, agiudiceandrea commented on source/site/forusers/alldownloads.rst
> +  sudo wget -O/etc/apt/keyrings/qgis-archive-keyring.gpg https://download.qgis.org/downloads/qgis-archive-keyring.gpg
```suggestion
  sudo wget -O /etc/apt/keyrings/qgis-archive-keyring.gpg https://download.qgis.org/downloads/qgis-archive-keyring.gpg
```

2022-08-13 07:07 UTC, eshattow requested changes
1. I think remove
`sudo mkdir -p /etc/apt/keyrings && sudo chmod 755 /etc/apt/keyrings`
and substitute with
`sudo mkdir -m755 -p /etc/apt/keyrings # not needed since apt version 2.4.0 like Debian 12 and Ubuntu 22 or newer`

This comment about apt version 2.4.0 has its source of information for reference in this review per https://metadata.ftp-master.debian.org/changelogs//main/a/apt/apt_2.5.2_changelog:
```
apt (2.4.0) unstable; urgency=medium
... * Install an empty /etc/apt/keyrings directory.
```
2. It is my opinion that qgis-archive-keyring.gpg file must be verified (in the meaning that it is a valid file and operable not corrupted in download) before installing to the system. Remove that suggestion about skipping verification from the document and it actually makes things clearer to understand also avoiding wget as root.

3. There are some (minor) whitespace changes, is that intentional?

2022-08-14 12:25 UTC, eshattow approved these changes

2022-08-15 22:38 UTC, agiudiceandrea commented
Was this PR already merged? https://github.com/qgis/QGIS-Website/commit/1ee53d3a34042e3a3e65cada560d55916db9844b

2022-08-16 09:10 UTC, nicogodet commented
I guess
It's live on https://www.qgis.org/fr/site/forusers/alldownloads.html#debian-ubuntu

2022-08-16 18:19 UTC, closed without merging