Download page simplification
qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one pull request #1046
Opened 2022-08-25 21:03 UTC by faebebin

![qgis-website-downloads](https://user-images.githubusercontent.com/21113500/186767926-6a0e17c6-c363-40cc-a6bf-300f41b802f2.gif)

Also adapted the Max-OS section for convenience. Else the css would have to be doubled.

![image](https://user-images.githubusercontent.com/21113500/186768080-0930ba5d-e459-43e4-bbf4-e910d6bd802c.png)

Moved the SHA256 links to all-downloads. Please check the .rst implementation , never worked with sphinx / .rst before.

2022-08-25 21:09 UTC, faebebin commented on source/site/forusers/alldownloads.rst
>    |                   | |releasenote|                +------------------------+-------------------------------------------------------+
please check whether this is true in all cases, as the jinja implementation was `release|e` instead of `version` etc ...

2022-08-27 15:02 UTC, haubourg commented on source/site/forusers/alldownloads.rst
>    |                   | |releasenote|                +------------------------+-------------------------------------------------------+
@faebebin I have no clue about which variable to use. @jef-n or @rduivenvoorde do you know more about the above question?

2022-08-27 15:03 UTC, haubourg commented
Nice work Fabiano.  I streamlined again more, removing redundant informations. Should I send you a patch or submit a PR to your fork ? 
![image](https://user-images.githubusercontent.com/1629853/187035898-e6782e16-8c72-4d5a-a81b-3ec68ea0a840.png)

2022-08-27 15:12 UTC, haubourg commented
[patch.zip](https://github.com/qgis/QGIS-Website/files/9438202/patch.zip)

here is a good old patch :) (my train arrives at destination )

2022-08-27 15:33 UTC, m-kuhn commented on themes/qgis-theme/forusers_download.html
> +                            </div>
```suggestion
                              <div class="{{ "qgis{}-download".format( "2" if version.startswith("2.") else "" ) }}"></div>
                              <div class="download-text">{{ _('OSGeo4W Network Installer') }}</div>
```

I'd suggest to stick to one single download button (and make the other one a link)

2022-08-28 00:20 UTC, faebebin commented on themes/qgis-theme/forusers_download.html
> +                            </div>
Thanks for improvements, wil have a close look soon

2022-08-28 13:04 UTC, m-kuhn commented on themes/qgis-theme/forusers_download.html
> +                      <div class="card">
```suggestion
```

Should we keep it all on one card?

2022-08-28 13:07 UTC, m-kuhn commented on themes/qgis-theme/forusers_download.html
> +                            </div>
```suggestion
                          <a class="secondary-download-link" href="https://download.osgeo.org/osgeo4w/v2/osgeo4w-setup.exe">
                            {{ _('OSGeo4W Network Installer') }}
```

2022-08-28 13:10 UTC, m-kuhn commented on themes/qgis-theme/forusers_download.html
> +                        <a class="btn btn-large" href="https://qgis.org/downloads/QGIS-OSGeo4W-{{ release|e }}-{{ binary|e }}.msi">
```suggestion
                        <a class="btn btn-large btn-success" href="https://qgis.org/downloads/QGIS-OSGeo4W-{{ release|e }}-{{ binary|e }}.msi">
```

+ change css for icon-large to a white logo (see https://qgis.org/en/_downloads/33f050ac04289004b33a4b296306d781/qgis-icon-white64.png)

2022-08-28 13:11 UTC, m-kuhn commented
![image (16)](https://user-images.githubusercontent.com/588407/187075695-8c15743f-3c61-4c84-aeff-b6d58289a37a.png)

result of some playing here

2022-08-28 13:12 UTC, m-kuhn commented
We should also move the "Note" to sit at the bottom

2022-08-28 14:38 UTC, haubourg commented
mm, I like this greenish button. 

+1 for moving the note at the bottom, this was in my patch :)

2022-08-28 16:07 UTC, jef-n commented
Why move the SHA256 away from the standalone installers?  They are unrelated to the osgeo4w packages.

2022-08-28 18:16 UTC, haubourg commented
Well the feedback and discussion was to make the main download page as simple as possible. It is currently a bit crowded.  Sha checksums are useful in rare occasions. Having them in the advanced download page is probably enough. I know a lot of users that don't have a clue at all of what it is.

2022-08-29 12:32 UTC, faebebin commented
> Why move the SHA256 away from the standalone installers? They are unrelated to the osgeo4w packages.

was actually @andreasneumann suggestion. And I think majority agrees with it...

2022-08-29 13:29 UTC, faebebin commented
Thanks @haubourg  and @m-kuhn for improvements. I also applied the new download button to mac section (without any effort)  for following result:

2022-08-29 13:42 UTC, haubourg commented
Nice, did you apply my patch? I see some strings I removed. Alternatively, I'll open a PR to your branch, tell me what's better for you

2022-08-29 14:01 UTC, faebebin commented
I tried to apply but got an error on html generation. And then I just applied @m-kuhn suggestions.

2022-08-29 14:02 UTC, faebebin commented
Yes, open a PR

2022-09-02 09:48 UTC, faebebin commented
@m-kuhn , @haubourg , I applied the patch. Changes to windows download section from

![image](https://user-images.githubusercontent.com/21113500/188113321-fa7d519b-0e11-4f39-be28-435a6dca3c91.png)

to

![image](https://user-images.githubusercontent.com/21113500/188113106-c9b66c24-86f0-46d5-9989-65c8ffdda7e5.png)

2022-09-02 11:50 UTC, haubourg commented
Thanks @faebebin 

We need some spacing improvements I think. Can you merge "Standalone .. " and "NOTE: ..." into a single short line like 
`Standalone installers are recommander for new users (requires Windows >= 8. W7 not longer supports python 3.9 )`

And the link to the osgeo4w installer should be closer to its note.  
After this, I'll be quite happy :)


![image](https://user-images.githubusercontent.com/1629853/188132867-c7aa7738-83c4-4402-bc1a-17c321720877.png)

2022-09-02 12:15 UTC, andreasneumann commented
I think it should be

"not longer" should be "no longer" in the sentence "Python W7 not longer supports ..."

2022-09-02 14:00 UTC, DelazJ commented
And probably `Windows 7` instead of `Python W7`? Btw, is it not Python that dropped W7 support 😈?

2022-09-02 14:03 UTC, DelazJ commented
The note as in https://github.com/qgis/QGIS-Website/pull/1046#issuecomment-1229454434 looks nice to me...

2022-09-02 14:48 UTC, jef-n commented
> Btw, is it not Python that dropped W7 support 😈?

What do you mean?

2022-09-02 15:19 UTC, DelazJ commented
> What do you mean?

nitpicking: `W7 no longer supports python 3.9` vs `Python 3.9 (does not | no longer) support W7` are probably not the same thing.

2022-09-02 15:46 UTC, jef-n commented
> nitpicking: `W7 no longer supports python 3.9` vs `Python 3.9 (does not | no longer) support W7` are probably not the same thing.

Sorry - I missed the question mark and read "it is not Python that dropped W7 support".

2022-09-02 16:17 UTC, faebebin commented
I tried to implement all comments. I squashed and force pushed for easing conflict resolving.

Would now look like this:

![image](https://user-images.githubusercontent.com/21113500/188196297-bf0007dd-baf5-407b-93c9-077334379bb0.png)

2022-09-02 16:36 UTC, haubourg commented
I like it. @m-kuhn @timlinux @mbernasocchi @jef-n @rduivenvoorde how does this main download page looks like to you?

2022-09-02 20:36 UTC, jef-n commented
> Sorry - I missed the question mark and read "it is not Python that dropped W7 support".

But speaking of which I found https://github.com/nalexandru/api-ms-win-core-path-HACK, which makes Python 3.9 work on W7 again (not sure to what extent, but seems to work) - it's also in OSGeo4W now (but nothing depends on it).

2022-09-02 21:09 UTC, jef-n requested changes

2022-09-02 21:09 UTC, jef-n commented on source/site/forusers/alldownloads.rst
>    |                   | |releasenote|                +------------------------+-------------------------------------------------------+
Please revert the changes to alldownloads.rst.    The checksums of the standalones don't belong there.

2022-09-02 21:09 UTC, jef-n commented on themes/qgis-theme/forusers_download.html
> +                        <h5>{{ _('Alternative build') }}</h5>
The alternative builds are old.  They should be less emphasized that the LTR (or could IMHO just be removed as they are also mentioned on alldownloads)

2022-09-03 12:09 UTC, haubourg commented
> > Sorry - I missed the question mark and read "it is not Python that dropped W7 support".
> 
> But speaking of which I found https://github.com/nalexandru/api-ms-win-core-path-HACK, which makes Python 3.9 work on W7 again (not sure to what extent, but seems to work) - it's also in OSGeo4W now (but nothing depends on it).

interesting. Embedding it in the installer would solve the issue ?  I'm a bit worried this could be spotted as something too hacky by antiviruses. As W7 is EOL do you think it is worth spending time on this ?

2022-09-03 18:26 UTC, jef-n commented
> interesting. Embedding it in the installer would solve the issue ? I'm a bit worried this could be spotted as something too hacky by antiviruses. As W7 is EOL do you think it is worth spending time on this ?

Who for some reason still want/has to use W7, can install the package from OSGeo4W and hope for the best.  No sure what happens if you install it on >W7 - so I didn't plan on spending more time on this (or to put it into a standalone).

2022-09-03 19:37 UTC, DelazJ commented on themes/qgis-theme/forusers_download.html
> +                        <h5>{{ _('Alternative build') }}</h5>
> could IMHO just be removed as they are also mentioned on alldownloads

Agreed

2022-09-06 10:00 UTC, jef-n approved these changes

2022-09-06 10:02 UTC, faebebin commented
@jef-n , @DelazJ , @haubourg , further simplified the download sections according above discussion:
* removed sha256 from alldownloads
* removed Mac OS alternative builds
* adapted and simplified Mac OS Section like Windows section

2022-09-06 12:09 UTC, haubourg commented
That's a big +1 for me too

2022-09-06 12:14 UTC, m-kuhn commented
If there are no objections, let's merge it this week

2022-09-06 12:20 UTC, andreasneumann commented
> If there are no objections, let's merge it this week

Personally, I would like the LTR to be advertised as the "default" and not the regular releases. They are more stable, offer a better experience for new users and it is the "de facto" standard in organizations and companies.

With the regular releases, esp. the .0 and .1 releases it is more of a "game" if they work or not.

2022-09-06 12:37 UTC, m-kuhn commented
Shall we do a voting?

React :heart: for regular release (3.26) and :rocket: for ltr (3.22)

2022-09-06 12:40 UTC, andreasneumann commented
> Shall we do a voting?

Not sure if the github crowd is a representative group for the global QGIS user base ... but it is always good to "fell the pulse".

2022-09-06 12:42 UTC, m-kuhn commented
@andreasneumann a bigger redesign of the website is going on in parallel, so the decision here is only for the timeframe until that lands anyway (CC @timlinux )

2022-09-06 12:45 UTC, jef-n commented
@m-kuhn you can remove one vote ;)

2022-09-06 12:47 UTC, haubourg commented
As already shared with some of you, my point of view as a user and a former GIS administrator in charge of deploying QGIS for organisations, I vote to push the Release first. 
Why?
Because I think individual users are more seeking for the latest features and we need them to test it. So that LTR are more stable afterwards. And also because IT folks that choose to deploy a software know about LTS/LTR wording, when most users don't. They will be touched by the gentle nudge "Looking for more stable version?" . 

And in the end, if we are afraid that release are too much instable, we now have the "release candidate" wording in the splash screen and I hope no IT guy would deploy it with such a message. (I know, some will.. but hey... )

2022-09-06 12:58 UTC, andreasneumann commented
> Looking for more stable version?

But it doesn't read that way currently, it says "looking for long term support". It doesn't tell the users that LTRs are more stable.

2022-09-06 13:46 UTC, anitagraser commented
> I think individual users are more seeking for the latest features and we need them to test it. 

I wonder how useful it is to "trick" users into being testers. I think involuntary testers are unlikely to report bugs. At most, they complain about "the buggy os software" on social media.

2022-09-06 14:01 UTC, haubourg commented
> I wonder how useful it is to "trick" users into being testers. I think involuntary testers are unlikely to report bugs. At most, they complain about "the buggy os software" on social media.

Oh, sorry I didn't mean that we want to trick users into testers. Not at all.
Does this mean we are not confident enough in our releases?  I mean, ArcPro memes about freezes and crashes are legion. 
To me, the "release early , release often" philosophy is a strong point of open source software and diverting the biggest user base to the old versions is synonym to avoid benefiting of this advantage. 

Another way of saying this:  I tried for a long time now to convince organisations to use stabilized LTR's and use the small remaining time frame to have bug fixed through support contracts. But in reality, only a small fraction plays the game, which means the biggest user base is not helping us into stabilizing.  

When I download any other software, I expect the latest version first and I struggle to find examples where project pushes older versions first. Why would QGIS.org do that? 
Distributions on Linux play that game of selecting stable or bleeding age versions, not the software themselves.  


> But it doesn't read that way currently, it says "looking for long term support".

totally, we can rephrase this to "Looking for more stable version?" if it looks clearer . But it would looks a bit negative to me

2022-09-06 14:28 UTC, m-kuhn commented
> Does this mean we are not confident enough in our releases? I mean, ArcPro memes about freezes and crashes are legion. To me, the "release early , release often" philosophy is a strong point of open source software and diverting the biggest user base to the old versions is synonym to avoid benefiting of this advantage.

This is the key point to me. If we don't trust our releases we should take a step back and think what we can do to either improve stability or change the label. But this seems out of scope for the discussion here.

To me: we currently call them release so I am comfortable with offering them for downloading.

> > But it doesn't read that way currently, it says "looking for long term support".
> 
> totally, we can rephrase this to "Looking for more stable version?" if it looks clearer . But it would looks a bit negative to me

"Looking for the most stable version"?

2022-09-06 15:50 UTC, andreasneumann commented
> This is the key point to me. If we don't trust our releases we should take a step back and think what we can do to either improve stability or change the label. But this seems out of scope for the discussion here.

Right - personally I think we need to improve the semi-automated testing before we really recommend the regular releases over LTR releases. It happened quite a few times that the .0 or .1 had major issues (like a broken library in the packaging, or a major crash or regression).

@SrNetoChan and @gioman wanted to introduce the semi-automated testing, but I believe the process is not yet established. Once that is done, I think we are in a much better position to avoid major pitfalls for packaged releases.

2022-09-06 19:11 UTC, nyalldawson commented on themes/qgis-theme/forusers_download.html
> +                      <p>{{ _('Standalone installers are recommended for new users. <em>Requires Windows 8 64 bit or higher because QGIS needs Python 3.9, which does no longer support Windows 7.') }}
```suggestion
                      <p>{{ _('Standalone installers are recommended for new users. <em>Requires Windows 8 64 bit or higher because QGIS requires Python 3.9 or later, which is not available for Windows 7.') }} </em></p>
```

2022-09-09 16:07 UTC, m-kuhn commented
@andreasneumann are you ok if this is merged -- to make the download page look better in the short term -- and to follow up with the discussion about quality improvement somewhere else?

2022-09-09 16:12 UTC, andreasneumann commented
> @andreasneumann are you ok if this is merged -- to make the download page look better in the short term -- and to follow up with the discussion about quality improvement somewhere else?

@m-kuhn  Yes - I am fine with the change. Thanks!

2022-09-09 16:19 UTC, merged

2022-09-10 07:08 UTC, agiudiceandrea commented
@jef-n, it seems to me the main download page and the "all download" page now miss the previously available instructions on how to correctly install the full QGIS and QGIS LTR using the OSGeo4W Network installer:

> In the installer choose Express Install and select QGIS to install the latest release or QGIS LTR to install the long term release.
> The express installations have several optional packages including non-free software. To avoid those you have to use the Advanced Install and choose qgis and/or qgis-ltr in the desktop section.

2022-11-04 11:08 UTC, agiudiceandrea commented
Hi @faebebin @m-kuhn, it seems to me this PR has an unintended and unwanted side effect: please see https://github.com/qgis/QGIS-Website/issues/1077.

2022-11-05 00:20 UTC, faebebin commented
@faebebin thanks for info. Will have a look asap