Ogc conformance testing
qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one pull request #403
Opened 2016-12-09 15:34 UTC by mhugent

This PR adds a quick tutorial how to setup the OGC confomance tests for WMS 1.3.0 and WMS 1.1.1

2016-12-09 15:57 UTC, yjacolin requested changes

2016-12-09 15:57 UTC, yjacolin commented on source/site/getinvolved/development/qgisdevelopersguide/ogcconformancetesting.rst
> +
could you add some index see http://docs.qgis.org/testing/en/docs/documentation_guidelines/writing.html#index

2016-12-09 15:57 UTC, yjacolin commented on source/site/getinvolved/development/qgisdevelopersguide/ogcconformancetesting.rst
> +sudo apt-get install openjdk-8-jdk
use .. code:: shell

2016-12-09 15:57 UTC, yjacolin commented on source/site/getinvolved/development/qgisdevelopersguide/ogcconformancetesting.rst
> +wget http://cite.opengeospatial.org/teamengine/about/wms/1.3.0/site/data-wms-1.3.0.zip
.. code:: shell

2016-12-09 15:57 UTC, yjacolin commented on source/site/getinvolved/development/qgisdevelopersguide/ogcconformancetesting.rst
> +export PATH=/usr/lib/jvm/java-8-openjdk-amd64/bin:$PATH
.. code:: shell

2016-12-09 15:57 UTC, yjacolin commented on source/site/getinvolved/development/qgisdevelopersguide/ogcconformancetesting.rst
> +export PATH=/usr/lib/jvm/java-8-openjdk-amd64/bin:$PATH
.. code:: shell

2016-12-09 15:57 UTC, yjacolin commented
thanks @mhugent!

2016-12-09 21:56 UTC, DelazJ commented on source/site/getinvolved/development/qgisdevelopersguide/ogcconformancetesting.rst
> +The Open Geospatial Consotrium (OGC) provides tests which can be run free of charge to make sure a server is compliant with a certain specification. This chapter provides a quick tutorial to setup th
_Typo_: Consortium
_Proposal_: use a hyperlinked text, namely \`OGC website \<http://www.opengeospatial.org/compliance>`_

To ease reading and review, lines should not be over 80 characters

2016-12-09 21:56 UTC, DelazJ commented on source/site/getinvolved/development/qgisdevelopersguide/ogcconformancetesting.rst
> +sudo apt-get install openjdk-8-jdk
If you go with the code block, then you can get rid of empty lines used between two following commands inside the block.

2016-12-09 21:56 UTC, DelazJ commented on source/site/getinvolved/development/qgisdevelopersguide/ogcconformancetesting.rst
> +#Download and install WMS 1.3.0 test
What does the # character stand for? A comment inside the code or numbering or something else...

2016-12-12 15:21 UTC, yjacolin approved these changes

2016-12-12 15:21 UTC, merged

2016-12-12 15:31 UTC, rldhont commented
@mhugent cool to see this. Do you have the QGIS project ? To run test ?

2016-12-12 15:39 UTC, mhugent commented
@rldhont: the project does not involve styling at all. Just download the zip file with the data and load all the shapefiles and geotiffs into a project (the layer names should already be okay). Then you can run the tests against that project.

2016-12-12 15:39 UTC, rldhont commented
@mhugent ok thanks!