some changes in the bugreporting page to reflect the new redmine forms
qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one pull request #430
Opened 2017-05-01 14:18 UTC by gioman

2017-05-01 14:30 UTC, yjacolin requested changes

2017-05-01 14:30 UTC, yjacolin commented on source/site/getinvolved/development/bugreporting.rst
> +* **Operating System** - Choose the platform you are using
`Choose the operating system you are using?` ?

2017-05-01 14:34 UTC, yjacolin approved these changes

2017-05-01 14:34 UTC, gioman commented on source/site/getinvolved/development/bugreporting.rst
> +* **Operating System** - Choose the platform you are using
good catch, I changed the wording.

2017-05-01 14:35 UTC, yjacolin commented
@gioman Feel free to merge after the checks are green or ping me if you have no commit right :) Thanks!

2017-05-01 18:13 UTC, gioman commented
@yjacolin I don't commit rights, can you merge this? thanks!

2017-05-01 18:40 UTC, DelazJ commented on source/site/getinvolved/development/bugreporting.rst
> +            used to work as expected and then stopped to work in more recent QGIS release)
these three lines should be aligned on \*High\* (see line 84)

2017-05-02 07:17 UTC, gioman commented on source/site/getinvolved/development/bugreporting.rst
> +            used to work as expected and then stopped to work in more recent QGIS release)
should be ok now

2017-05-02 07:28 UTC, merged

2017-05-02 07:28 UTC, DelazJ commented
Thanks