Add Clear Mapping Co to commercial_support.rst
qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one pull request #444
Opened 2017-06-07 13:15 UTC by nickbearman

Hi,

I'd like to add Clear Mapping Co to the commercial support page in this PR.

We're not a Core Contributors, but what are the criteria for Contributors?

We have sponsored a QGIS South West User Group meeting (http://www.clearmapping.co.uk/our-blog/item/457-qgis-south-west-user-group-event.html), and I (@nickbearmanuk) have made a small contribution to the QGIS Documentation a while a go. 

If we qualify for Contributors, great - I can update the PR. Otherwise we are very happy to be listed under 'Other'.

Best wishes,
Nick.

2017-06-07 13:20 UTC, nickbearman commented
Hi, the Travis CI check failed, but it flagged a file I haven't touched - /home/travis/build/qgis/QGIS-Website/source/site/about/case_studies/poland_ffth.rst
Is there anything I can do about this?
Sorry!
Best wishes,
Nick.

2017-06-07 18:09 UTC, DelazJ commented
Yes, website build was broken. Fixed now so reopening your PR should trigger a check only on your changes.

2017-06-08 07:22 UTC, yjacolin requested changes

2017-06-08 07:22 UTC, yjacolin commented on source/site/forusers/commercial_support.rst
> +.. |clearmapping| image:: /static/site/about/images/clear_mapping_co.jpg
it should be `|clear_mapping_co|` here or change below ;)

2017-06-13 09:32 UTC, nickbearman commented
Thanks @yjacolin for spotting the mistake - I have corrected it.

2017-06-13 09:32 UTC, nickbearman commented
Thanks @DelazJ for correcting the build process - all looks good now.

2017-06-13 15:56 UTC, DelazJ commented
Credits of build fixes go to @yjacolin and @rduivenvoorde . Thanks to them. I was simply the messenger :)

2017-06-20 13:37 UTC, nickbearman commented
Hi @yjacolin I think I've done all the changes you requested, do let me know if I have missed something!

2017-08-07 16:29 UTC, merged