clarify that ubuntugis-unstable is what we build against
qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one pull request #464
Opened 2017-09-06 15:31 UTC by mbernasocchi

made more clear that  the ubuntugis based repos need ubuntugis-unstable PPA

2018-01-06 16:26 UTC, yjacolin requested changes
@mbernasocchi would you mind to rebase your branch?

2018-05-23 07:16 UTC, mbernasocchi commented
@yjacolin done

2018-05-23 07:23 UTC, yjacolin commented
@mbernasocchi I think you need to change the table a little bitt as you add more letter in some rows!

2018-05-23 07:58 UTC, merged

2018-05-23 07:59 UTC, yjacolin commented
Thanks @mbernasocchi :)