link to instructions to install qgis from source
qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one pull request #497
Opened 2018-01-30 22:36 UTC by andrewharvey

As a user I wanted to install QGIS, went to this page on the website, but couldn't find the option to install QGIS from source, I think it will be useful to add this link for more advanced users who would prefer to install from source.

2018-01-31 08:27 UTC, yjacolin requested changes

2018-01-31 08:27 UTC, yjacolin commented on source/site/forusers/alldownloads.rst
> +To build and install QGIS from source see https://github.com/qgis/QGIS/blob/master/INSTALL
Could you use this link instead: http://htmlpreview.github.io/?https://raw.github.com/qgis/QGIS/master/doc/INSTALL.html

2018-02-13 13:07 UTC, andrewharvey commented on source/site/forusers/alldownloads.rst
> +To build and install QGIS from source see https://github.com/qgis/QGIS/blob/master/INSTALL
sure, I've changed the link

2018-02-13 13:18 UTC, yjacolin commented on source/site/forusers/alldownloads.rst
> +To build and install QGIS from source see https://github.com/qgis/QGIS/blob/master/INSTALL
thanks it could be even better if you can use something like 
```
[QGIS from source](http://htmlpreview.github.io/?https://raw.github.com/qgis/QGIS/master/doc/INSTALL.html).
```
Which will be displayed like this:
[QGIS from source](http://htmlpreview.github.io/?https://raw.github.com/qgis/QGIS/master/doc/INSTALL.html).
Sorry to forget this in my previous comment.

2018-02-13 13:29 UTC, andrewharvey commented on source/site/forusers/alldownloads.rst
> +To build and install QGIS from source see https://github.com/qgis/QGIS/blob/master/INSTALL
I've used similar wording as the Sources tab at https://www.qgis.org/en/site/forusers/download.html. For some reason I never found that tab and only found the guide at https://www.qgis.org/en/site/forusers/alldownloads.html.

2018-02-13 13:32 UTC, yjacolin commented
@andrewharvey sorry I was wrong about the tags element. I updated your branch directly. I will merge it after the test. Thanks a lot!

2018-02-13 13:34 UTC, yjacolin approved these changes

2018-02-13 13:34 UTC, merged