QGIS is GPLv2+
qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one pull request #875
Opened 2021-03-02 12:59 UTC by vpicavet

We should make it clear in the contributor guidelines that QGIS is GPL version 2 or above, as stated in the project's README.

2021-03-15 09:20 UTC, mach0 commented on source/site/getinvolved/development/contributor_requirements.rst
> +  with the QGIS license, GPL version 2 or above
Hi. just stumbled across this and.. Isn't the term usually
GPL version 2 or later ?
That would sound more common to me.

2021-03-15 09:32 UTC, vpicavet commented on source/site/getinvolved/development/contributor_requirements.rst
> +  with the QGIS license, GPL version 2 or above
I took the expression from the project's README. I agree that "or later" is more frequently used. I would just try to keep a coherency, and change the README if we use "or later" here too.

2021-03-16 19:48 UTC, mach0 commented on source/site/getinvolved/development/contributor_requirements.rst
> +  with the QGIS license, GPL version 2 or above
the most used term I could find everywhere was: GNU Public License (GPL) Version 2 or any later version.
and that sounds nice and is also now stated in the README of QGIS.
If you'd like to change that I am going to pull the last PR in ;)

2021-03-20 08:49 UTC, agiudiceandrea requested changes

2021-03-20 08:49 UTC, agiudiceandrea commented on source/site/getinvolved/development/contributor_requirements.rst
> +  with the QGIS license, GPL version 2 or above
```suggestion
  with the QGIS license, GNU Public License (GPL) Version 2 or any later version.
```

2021-03-21 17:23 UTC, merged