add facebook community link
qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one pull request #954
Opened 2021-12-07 20:37 UTC by mbernasocchi

As per PSC decision, adding the link to the FB group has over 50K members and is probably one of the biggest community group we have

2021-12-16 14:31 UTC, jonnyforestGIS requested changes
Gentle ping @mbernasocchi. 
Adelcides Varela ask me if is possible to change the link in this PR to the new oficial Facebook Group url:
https://www.facebook.com/groups/qgiscommunityofficialusergroup/

Cheers

2021-12-16 14:54 UTC, rduivenvoorde commented
Guys, sorry to say, but this is really a gated community...

They let you in for a certain time/posts, and after that visiting you get the image below

![Screenshot-20211216154945-917x842](https://user-images.githubusercontent.com/731673/146394044-f7bdf872-a98c-49e1-86ce-b2add55c1e67.png)

2021-12-16 15:38 UTC, adelcidesvarela commented
> Guys, sorry to say, but this is really a gated community...
> 
> They let you in for a certain time/posts, and after that visiting you get the image below
> 
> ![Screenshot-20211216154945-917x842](https://user-images.githubusercontent.com/731673/146394044-f7bdf872-a98c-49e1-86ce-b2add55c1e67.png)

Hello there, thank you for the comment. Actually that is not the group itself that does that, it's a public group, but is in fact standard facebook/meta behaviour/policy. They did the same to instagram for example.

2021-12-16 16:29 UTC, rduivenvoorde commented
Mmm, it's really not my cup of tea :-)

2021-12-16 16:29 UTC, merged

2021-12-16 16:31 UTC, andreasneumann commented
> Mmm, it's really not my cup of tea :-)

neither mine. FB or Meta - or whatever it is called is one of the most evil companies in the world ...

2021-12-18 08:48 UTC, mbernasocchi commented
> Mmm, it's really not my cup of tea :-)

:) fully understand that @rduivenvoorde. The important thing here is that the group does a fantastic job at serving over 50K users that care about QGIS.